title: Project

files:
  sortable: true

pages: false

fields:
  title:
    label: Title
    type:  text
    width: 3/4

  year:
    label: Year
    type:  text
    width: 1/4

  category:
      label: Category
      type: select
      width: 1/3
      options:
        model: Model
        object: Object
        project: Project

  text:
    label: Text
    type:  textarea


  builder:
          label: images
          type: builder
          fieldsets:
            imageBanner:
              label: Image
              snippet: sections/imagebanner
              fields:
                image:
                  label: Image
                  type: image
                width:
                  width: 1/4
                  label: width
                  type: text
                  default: 1920
                height:
                  width: 1/4
                  label: height
                  type: text
                  default: 1080
                title:
                  label: Title
                  type: text
                description:
                  label: Description
                  type: textarea